# Generated by Django 5.1.7 on 2025-04-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
